### ISSUE TITLE
상태바에서 아이콘이 재대로 나오지 않는 버그

### ISSUE THREAD

**Issue by Hansanghyeon** [techinpark/Jandi#1]
- OS: macOS Big Sur 11.2
 - 설치: App store

상태 바에서 아이콘이 제대로 나오지 않는 버그가 있습니다.

처음에 작동이 안 되는 것인가 살펴보았는데 아이콘이 없어서 못 찾았었네요

<img width="1920" alt="스크린샷 2021-02-04 오후 4 50 39" src="https://user-images.githubusercontent.com/42893446/106861666-66ae5600-6709-11eb-95f9-da26fe97432c.png">

**Comment by techinpark** [comment]
@Hansanghyeon 이슈 올려주셔서 감사합니다! 확인해보고 패치하겠습니다 👍🏻

**Comment by techinpark** [comment]
@Hansanghyeon 말씀해주신 이슈 수정되어 다음버전인 `v1.2`에 반영될 예정입니다. 해당 이슈는 클로즈 처리하겠습니다 감사합니다 🙇
