### ISSUE TITLE
1일 1커밋 카운트가 되지 않는 것 같습니다.

### ISSUE THREAD

**Issue by cow-coding** [techinpark/Jandi#12]
# **Describe the bug**
1.7 버전 업데이트 진행했고 현재 3일 연속 커밋했으나 카운트 진행 안되는 것 같습니다.

# **Screenshots**

<img width="264" alt="스크린샷 2021-03-10 오후 6 10 34" src="https://user-images.githubusercontent.com/61653740/110605224-3bb59700-81cc-11eb-9b3a-1c5b0f7c0397.png">

혹시 제가 1일 1커밋 사용을 잘못 이해하고 있나요?

**Comment by techinpark** [comment]
@5anniversary 한번 확인 부탁드려도 될까요?

**Comment by 5anniversary** [comment]
확인해보겠습니다 🙂

**Comment by techinpark** [comment]
@cow-coding @5anniversary 이슈제보 와 빠른 이슈수정 모두 감사드립니다 `v1.8` 버전에 반영될 예정입니다 🥳
