### ISSUE TITLE
이모지가 표시되지 않습니다.

### ISSUE THREAD

**Issue by M1zz** [techinpark/Jandi#15]
**Additional context**
? 잔디가 무럭무럭 자란지 30일이 되었어요 라고 나옵니다.

**Comment by 5anniversary** [comment]
@M1zz 
안녕하세요! 혹시 사용하시는 OS가 어떤 버전인지 궁금한데 알려주실수있나요?

지금 확인해보니 해당 이모지가 iOS 14.2 부터 새로 제공되는 이모지로 확인이 되네요.

**Comment by 5anniversary** [comment]
추가로 문제사항이 발생할 거 같으니 변경시키도록 하겠습니다.

**Comment by M1zz** [comment]
아하 제가 빅서로 올리지 않아서 생기는 문제였나봐요 ㅎ ㅎ
10.15.7 카탈리나 입니다!

**Comment by 5anniversary** [comment]
오늘내로 변경시켜서 PR 날리겠습니다 ㅎㅎ

잠시만 기다려주세요!
