### ISSUE TITLE
Github와 Jandi에서의 실제 commit 횟수가 다른날짜가 있습니다.

### ISSUE THREAD

**Issue by GGOOLTAE** [techinpark/Jandi#18]
**Describe the bug**

**Screenshots**
- Jandi 앱의 commit 횟수
![image](https://user-images.githubusercontent.com/33389245/152711759-21c7d442-71e7-417a-b198-ec0022a95a33.png)
- Github에서본 2월5일의 commit 횟수
![image](https://user-images.githubusercontent.com/33389245/152712371-9b42f879-fdaf-4039-843d-eacbce4d7638.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version  : Monterey 12.2

**Additional context**
첨부된 이미지에서 보이듯, 2월5일 github에서본 commit수와, jandi의 commit수가 다릅니다.
또한, 일치하지않는 경우가 더 있습니다.
※ Github Desktop App을 통해 Push 하고있습니다.

**Comment by techinpark** [comment]
@GGOOLTAE 안녕하세요! 혹시 private repository에 커밋을 하신건지 확인 부탁드려도 될까요?

**Comment by GGOOLTAE** [comment]
@techinpark 에고,, 제가 실수했네요😅  
확인해주셔서 감사합니다!

**Comment by techinpark** [comment]
@GGOOLTAE https://github.com/techinpark/Jandi/issues/9 링크를 참고해보시면 private 커밋도 표시할 수 있는 옵션을 켜주시면 정상 반영 될 것 같습니다!

**Comment by GGOOLTAE** [comment]
@techinpark TIP 감사합니다. 😀
