### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YangJinmo** [techinpark/Jandi#25]
**Describe the bug**
잘 사용하고 있었는데 오늘 보니까 갑자기 안됩니다!

**Screenshots**
![image](https://user-images.githubusercontent.com/81158331/210924158-8c01720c-a944-48a2-ac6b-9dd94778206a.png)

**Desktop**
 - OS: macOS Ventura 13.1(22C65)
 - Browser: chrome

**Comment by techinpark** [comment]
@YangJinmo 말씀해주신 이슈 수정되어 스토어 심사중이고 바로 사용해보시려면 릴리즈에 있는 v1.11버전 이용해주시면 될것 같아요 감사합니다 🙏
