### ISSUE TITLE
정보를 불러오지 못함

### ISSUE THREAD

**Issue by felix-0608** [techinpark/Jandi#27]
![image](https://user-images.githubusercontent.com/107231513/211242370-3cdf9d45-d380-4deb-aace-b077d57cdcff.png)

내 잔디 정보 및 친구의 잔디 정보를 불러오지 못하고있습니다. 
새로고침 및 프로그램을 재시작해도 동일한 현상이 나오며 다른 Mac도 동일한 상태입니다.

 - OS: macOS
 - Version: Ventura 13.0.1

**Comment by techinpark** [comment]
@felix-0608 최신버전으로 업데이트 부탁드립니다!
