### ISSUE TITLE
깃허브를 불러오지 못함

### ISSUE THREAD

**Issue by HongSJae** [techinpark/Jandi#31]
**Describe the bug**
깃허브에서 커밋 정보를 가져오지 못합니다.

**To Reproduce**
1. Go to 'Jandi'
2. I can't see my commit info, my friends too

**Screenshots**
<img width="313" alt="스크린샷 2023-11-20 오전 8 34 02" src="https://github.com/techinpark/Jandi/assets/102791216/60e20a74-a262-4d05-8b9d-6c3c90cba380">

**Desktop (please complete the following information):**
 - OS: [Mac OS]

**Comment by techinpark** [comment]
@HongSJae 사용중이신 앱 버전 정보 남겨주실 수 있을까요?

**Comment by HongSJae** [comment]
> @HongSJae 사용중이신 앱 버전 정보 남겨주실 수 있을까요?

1.13입니다. App Store에 업데이트가 뜨지 않아요

**Comment by techinpark** [comment]
@HongSJae Github에 변경사항이 있어 해당사항 반영한 업데이트가 필요하네요 제보해주셔서 감사합니다!

**Comment by techinpark** [comment]
@HongSJae #32 를 통해서 수정되었습니다 앱스토어 1.14 버전 업데이트 되시면 받아보실 수 있을거에요 제보 감사드립니다 😄

**Comment by HongSJae** [comment]
고생하셨습니다!!
