### ISSUE TITLE
잔디를 심어도 0인 문제

### ISSUE THREAD

**Issue by pozafly** [techinpark/Jandi#33]
## Screenshots
<br/>

**GitHub commit**

<img width="255" alt="image" src="https://github.com/techinpark/Jandi/assets/59427983/bac380db-d4af-433e-ac73-be65bd3ca701">

<br/><br/>

**Jandi**

<img width="285" alt="스크린샷 2023-11-20 오후 10 00 08" src="https://github.com/techinpark/Jandi/assets/59427983/d89be3ac-1ced-4d5b-9d4f-a4d74e79884b">

<br/>

## Desktop (please complete the following information)
 - OS: MacOS ventura 13.6(22G120)

## Issue

GitHub commit을 남기면 GitHub에는 정상적으로 commit 갯수가 표현되지만 Jandi에서는 현재 표현되고 있지 않습니다.
다른 GitHub commit 체크 어플리케이션도 마찬가지로 지난 주부터 기록이 되고 있지 않는 것을 보아, GitHub 측 API가 변경된 것으로 보입니다.
해결이 필요할 것 같습니다 :)

**Comment by techinpark** [comment]
@pozafly 1.14버전 스토어에서 업데이트 해주시면 될것 같습니다 감사합니다!

**Comment by pozafly** [comment]
감사합니다. close된 이슈를 미처 파악하지 못했었습니다. 고쳐주셔서 감사합니다! :)
