### ISSUE TITLE
Commit을 해도 최상단 문구가 "아직 잔디를 심지 못했어요."라고 문구가 나옵니당 

### ISSUE THREAD

**Issue by Jeon0976** [techinpark/Jandi#34]
**Describe the bug**
커밋하고나서 Mac의 상태창, 상세보기 클릭 후 요일별 커밋 수 등은 잘 보이는데 
목표달성 위 상태는 계속 커밋이 하나도 안 되었는 상태로 유지되고있습니다. 

**Screenshots**
<img width="178" alt="스크린샷 2023-12-01 16 15 07" src="https://github.com/techinpark/Jandi/assets/113761591/c472d54a-8ec4-4454-9546-00ac97ec516f">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5
 - Version AppStore: 1.14

**Additional context**
좋은 앱 잘 사용하고있습니다. 항상 감사드립니다.

**Comment by techinpark** [comment]
@Jeon0976  제보 감사드려요! v1.15 버전에서 수정하여 배포될 예정입니다
이슈 수정이 너무 늦었습니다 🙇
