### ISSUE TITLE
날짜 갱신 이슈

### ISSUE THREAD

**Issue by 87kangsw** [techinpark/Jandi#4]
## Issue content
- 7일 오전 9시가 되었으나 날짜 표시가 6일까지만 되는 이슈

## Screenshot
![스크린샷 2021-02-07 오전 9 31 30](https://user-images.githubusercontent.com/6590255/107132987-4fe54a80-6927-11eb-9c00-9eb6356d7d51.png)

## Expectation
- 7일 데이터가 표시되어야 함

---

아래 부분에서 7일 데이터가 걸러지던데 이유가 있을까요?
```swift
if date != today.getAttributes()?.get(key: ParseKeys.date) { 
}
```

---

추가로 커밋을 하게 되면 잔디 수는 올라가지만 `NSMenuItem`이 추가되지 않아서 값이 다르네요
![스크린샷 2021-02-07 오전 9 36 42](https://user-images.githubusercontent.com/6590255/107133092-1c56f000-6928-11eb-86b7-5b07e4ba4fca.png)

**Comment by techinpark** [comment]
본래 의도는 `statusbar` 영역을 오늘의 커밋수로 채우고, 하단의 메뉴 아이템 영역을 이전날의 커밋을 보여주도록 하기위해 조건을 설정하였습니다. 많은 분들이 헷갈리시는 부분인것 같아 기여해주신부분 반영되면 좋겠네요 1.3 버전에 반영하겠습니다 🚀
