### ISSUE TITLE
Introduce auto-start menu

### ISSUE THREAD

**Issue by simp7** [techinpark/Jandi#8]
**Is your feature request related to a problem? Please describe.**
Currently when I want to start Jandi as mac starts, I should go to login Items in settings manually.

**Describe the solution you'd like**
I think introducing new menu that toggles to auto-launch the app when start mac.

**Describe alternatives you've considered**
I don't know much about Apple's policy for auto-lauching app, but I saw that some apps just introduce to login items menu rather than directly make app auto-launchable.

**Comment by techinpark** [comment]
@simp7  Thank you for good suggestion!, We will support this feature. 😄

**Comment by junho85** [comment]
https://github.com/sindresorhus/LaunchAtLogin
It might be helpful.

**Comment by techinpark** [comment]
@junho85 Thanks for good suggestion!

**Comment by techinpark** [comment]
@simp7 @junho85  Thank you for your contribution. Released to 1.7 version. 🎉
