### ISSUE TITLE
I suggest my idea about updating commit count.. :)

### ISSUE THREAD

**Issue by Yeonlisa** [techinpark/Jandi#9]
I would like it to be updated in real time every time I commit.
The commit seems to be reflected only after rebooting..

**Comment by techinpark** [comment]
@Yeonlisa Thanks for good idea. 
but I suggest to use refresh feature. 
because we can't catch new commit events in real time.

```
- 1. tap jandi.app 
- 2. tap Refresh or [ CMD + R ] 
```
<img src="https://user-images.githubusercontent.com/45546296/110201367-09dbc200-7ea6-11eb-8ecd-00bbe75d0f97.png" width="50%">

**Comment by Yeonlisa** [comment]
eoseoyo
It was suggested because it was not reflected even when I clicked the refresh button.
I was wondering if it would be helpful for daily statistics if it was reflected in real time

**Comment by techinpark** [comment]
@Yeonlisa Oh! Are you working in a private repository?

**Comment by Yeonlisa** [comment]
Yes! I am still a student, so I mainly use the private repository.
Is this part only for public?

**Comment by techinpark** [comment]
![image](https://user-images.githubusercontent.com/45546296/110202210-7fe22800-7eaa-11eb-8494-775e50852469.png)

@Yeonlisa can you try it ? you can setup this options in profile page.

**Comment by Yeonlisa** [comment]
Oh! I got it!
Thank you so much!! :)
